approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  serwist@*:
    peerDependencies:
      workbox-background-sync: "*"
      workbox-broadcast-update: "*"
      workbox-cacheable-response: "*"
      workbox-core: "*"
      workbox-expiration: "*"
      workbox-precaching: "*"
      workbox-range-requests: "*"
      workbox-routing: "*"
      workbox-strategies: "*"
